create database QL_ThuVien1
go
USE QL_ThuVien1
GO

--TẠO BẢNG
CREATE TABLE KESACH
(
	MaKe VARCHAR(10) PRIMARY KEY,
	TenKe VARCHAR(100) NOT NULL
);

CREATE TABLE DOCGIA
(
	MaDocGia VARCHAR(10) PRIMARY KEY,
	TenDocGia NVARCHAR(100) NOT NULL,
	NgaySinh DATE NOT NULL,
	SDT VARCHAR(15) NOT NULL,
	DiaChi NVARCHAR(255) DEFAULT NULL,
	NgayDangKy DATE NOT NULL,
	CapThanhVien NVARCHAR(50) DEFAULT 'Bạc'
);

CREATE TABLE NXB
(
	MaNXB VARCHAR(10) PRIMARY KEY,
	TenNXB NVARCHAR(100) NOT NULL
);

CREATE TABLE TACGIA
(
	MaTacGia VARCHAR(10) PRIMARY KEY,
	TenTacGia NVARCHAR(100) NOT NULL,
	MoTa NVARCHAR(255) NOT NULL
);

CREATE TABLE THELOAISACH
(
	MaLoai VARCHAR(10) PRIMARY KEY,
	TenLoai NVARCHAR(100) NOT NULL
);

CREATE TABLE SACH
(
	MaSach VARCHAR(10) PRIMARY KEY,
	TenSach NVARCHAR(100) NOT NULL,
	MaNXB VARCHAR(10) FOREIGN KEY REFERENCES NXB(MaNXB),
	MaLoai VARCHAR(10) FOREIGN KEY REFERENCES THELOAISACH(MaLoai),
	MoTa NVARCHAR(255) NOT NULL,
	TinhTrang NVARCHAR(50) DEFAULT 'Bình thường',
	MaKe VARCHAR(10) FOREIGN KEY REFERENCES KESACH(MaKe)
);

CREATE TABLE THAMGIA
(
	MaTacGia VARCHAR(10) FOREIGN KEY REFERENCES TACGIA(MaTacGia),
	MaSach VARCHAR(10) FOREIGN KEY REFERENCES SACH(MaSach),
	PRIMARY KEY(MaTacGia, MaSach)
);

CREATE TABLE PHIEUMUON
(
	MaPhieuMuon VARCHAR(10) PRIMARY KEY,
	MaDocGia VARCHAR(10) FOREIGN KEY REFERENCES DOCGIA(MaDocGia),
	NgayMuon DATE
);

CREATE TABLE CHITIETPHIEUMUON
(
	MaCTPM VARCHAR(10) PRIMARY KEY,
	MaPhieuMuon VARCHAR(10) NOT NULL FOREIGN KEY REFERENCES PHIEUMUON(MaPhieuMuon),
	MaSach VARCHAR(10) NOT NULL FOREIGN KEY REFERENCES SACH(MaSach)
);

CREATE TABLE PHIEUTRA
(
	MaPhieuTra VARCHAR(10) PRIMARY KEY,
	MaDocGia VARCHAR(10) FOREIGN KEY REFERENCES DOCGIA(MaDocGia),
	MaSach VARCHAR(10) FOREIGN KEY REFERENCES SACH(MaSach),
	NgayTra DATE
);

CREATE TABLE NCC
(
	MaNCC VARCHAR(10) PRIMARY KEY,
	TenNCC NVARCHAR(100) NOT NULL
);

CREATE TABLE NHAPSACH
(
	MaNhap VARCHAR(10) PRIMARY KEY,
	MaNCC VARCHAR(10) FOREIGN KEY REFERENCES NCC(MaNCC),
	NgayNhap DATE NOT NULL
);

CREATE TABLE CHITIETNHAPSACH
(
	MaCTNS VARCHAR(10) PRIMARY KEY,
	MaNhap VARCHAR(10) FOREIGN KEY REFERENCES NHAPSACH(MaNhap),
	MaSach VARCHAR(10) FOREIGN KEY REFERENCES SACH(MaSach),
	DonGia INT CHECK (DonGia > 0),
	SoLuong INT CHECK (SoLuong > 0)
);

