-- Tạo cơ sở dữ liệu
CREATE DATABASE QL_ThuVien;
GO

USE QL_ThuVien;
GO

-- TẠO BẢNG KESACH
CREATE TABLE KESACH
(
    MaKe VARCHAR(10) PRIMARY KEY, 
    TenKe VARCHAR(50) NOT NULL
);

-- TẠO BẢNG DOCGIA
CREATE TABLE DOCGIA
(
    MaDocGia VARCHAR(10) PRIMARY KEY, 
    TenDocGia NVARCHAR(100) NOT NULL,
    NgaySinh DATE NOT NULL,
    SDT VARCHAR(11) NOT NULL,         
    DiaChi NVARCHAR(255) NOT NULL,
    NgayDangKy DATE NOT NULL,
    CapThanhVien NVARCHAR(50)
        DEFAULT 'Bạc'
);
GO

-- TẠO BẢNG NXB (Nhà Xuất Bản)
CREATE TABLE NXB
(
    MaNXB VARCHAR(10) PRIMARY KEY, 
    TenNXB NVARCHAR(100) NOT NULL
);

-- TẠO BẢNG TACGIA
CREATE TABLE TACGIA
(
    MaTacGia VARCHAR(10) PRIMARY KEY, 
    TenTacGia NVARCHAR(100) NOT NULL,
    MoTa NVARCHAR(255) NOT NULL
);
GO

-- TẠO BẢNG THELOAISACH
CREATE TABLE THELOAISACH
(
    MaLoai VARCHAR(10) PRIMARY KEY, 
    TenLoai NVARCHAR(50) NOT NULL
);

-- TẠO BẢNG SACH
CREATE TABLE SACH
(
    MaSach VARCHAR(10) PRIMARY KEY, 
    TenSach NVARCHAR(100) NOT NULL,
    MaNXB VARCHAR(10)
        FOREIGN KEY REFERENCES NXB (MaNXB),
    MaLoai VARCHAR(10)
        FOREIGN KEY REFERENCES THELOAISACH (MaLoai),
    MoTa TEXT NOT NULL,
    TinhTrang NVARCHAR(50)
        DEFAULT 'Bình thường',
    MaKe VARCHAR(10)
        FOREIGN KEY REFERENCES KESACH (MaKe)
);
GO

-- TẠO BẢNG THAMGIA (Tác giả tham gia viết sách)
CREATE TABLE THAMGIA
(
    MaTacGia VARCHAR(10)
        FOREIGN KEY REFERENCES TACGIA (MaTacGia),
    MaSach VARCHAR(10)
        FOREIGN KEY REFERENCES SACH (MaSach),
    PRIMARY KEY (
                    MaTacGia,
                    MaSach
                )
);

-- TẠO BẢNG PHIEUMUON
CREATE TABLE PHIEUMUON
(
    MaPhieuMuon VARCHAR(10) PRIMARY KEY, 
    MaDocGia VARCHAR(10)
        FOREIGN KEY REFERENCES DOCGIA (MaDocGia),
    NgayMuon DATE NOT NULL
);
GO

-- TẠO BẢNG CHITIETPHIEUMUON
CREATE TABLE CHITIETPHIEUMUON
(
    MaCTPM VARCHAR(10) PRIMARY KEY, 
    MaPhieuMuon VARCHAR(10) NOT NULL
        FOREIGN KEY REFERENCES PHIEUMUON (MaPhieuMuon),
    MaSach VARCHAR(10) NOT NULL
        FOREIGN KEY REFERENCES SACH (MaSach)
);
GO

-- TẠO BẢNG PHIEUTRA
CREATE TABLE PHIEUTRA
(
    MaPhieuTra VARCHAR(10) PRIMARY KEY, 
    MaDocGia VARCHAR(10)
        FOREIGN KEY REFERENCES DOCGIA (MaDocGia),
    MaSach VARCHAR(10)
        FOREIGN KEY REFERENCES SACH (MaSach),
    NgayMuon DATE NOT NULL
);
GO

-- TẠO BẢNG NCC (Nhà Cung Cấp)
CREATE TABLE NCC
(
    MaNCC VARCHAR(10) PRIMARY KEY, 
    TenNCC NVARCHAR(100) NOT NULL
);

-- TẠO BẢNG NHAPSACH (Nhập sách từ NCC)
CREATE TABLE NHAPSACH
(
    MaNhap VARCHAR(10) PRIMARY KEY, 
    MaNCC VARCHAR(10)
        FOREIGN KEY REFERENCES NCC (MaNCC),
    NgayNhap DATE NOT NULL
);
GO

-- TẠO BẢNG CHITIETNHAPSACH
CREATE TABLE CHITIETNHAPSACH
(
    MaCTNS VARCHAR(10) PRIMARY KEY, 
    MaNhap VARCHAR(10)
        FOREIGN KEY REFERENCES NHAPSACH (MaNhap),
    MaSach VARCHAR(10)
        FOREIGN KEY REFERENCES SACH (MaSach),
    DonGia INT CHECK (DonGia > 0),
    SoLuong INT CHECK (SoLuong > 0)
);
GO

-- TẠO BẢNG USERS (Người dùng)
CREATE TABLE TAIKHOAN
(
    Email VARCHAR(100) PRIMARY KEY,
    HashedPassword VARCHAR(255) NOT NULL,
    MaDocGia VARCHAR(10) UNIQUE NULL 
        FOREIGN KEY REFERENCES DOCGIA (MaDocGia) ON DELETE CASCADE,
    VaiTro VARCHAR(50) DEFAULT 'user'
);
GO

CREATE FUNCTION dbo.func_LayMaDocGiaLonNhat()
RETURNS VARCHAR(10)
AS
BEGIN
    DECLARE @MaxMaDocGia VARCHAR(10);

    SELECT @MaxMaDocGia = MAX(MaDocGia)
    FROM DOCGIA;

    -- Kiểm tra nếu không có độc giả nào, trả về '0'
    IF @MaxMaDocGia IS NULL
    BEGIN
        RETURN 'DG000';
    END

    RETURN @MaxMaDocGia;
END;
GO

CREATE FUNCTION dbo.func_GetChiTietSach (@MaSach NVARCHAR(50))
RETURNS TABLE
AS
RETURN
(
    SELECT 
        S.TenSach,
        NXB.TenNXB,
        s.MoTa,
        s.HinhAnh
    FROM 
        Sach S join NXB on NXB.MaNXB = S.MaNXB
    WHERE 
        MaSach = @MaSach
);

SELECT * FROM dbo.func_GetChiTietSach('S001');

Insert into TheLoaiSach
values
('L001',N'Thơ')
Insert into NXB
values
('NXB001',N'NXB Kim Đồng')
Insert into KeSach
values
('K001',N'Kệ thơ')
Insert into SACH
values
('S001',N'Truyện Kiều','1.jpg','NXB001','L001',N'Thơ của Nguyễn Du',2,'K001')
